###

GET http://localhost:3000/user

###

GET http://localhost:3000/task

###

GET http://localhost:3000/user?name=Daniel123

###
POST http://localhost:3000/user/login
Content-Type: application/json

{
    "email": "Danieva3@ac.sce.ac.il",
    "password": "123456"
}

###

POST http://localhost:3000/user
Content-Type: application/json

{
    "name": "Daniel123",
    "email": "Danieva3@ac.sce.ac.il",
    "password": "123456"
}

###

PUT http://localhost:3000/user

###

DELETE http://localhost:3000/user

###

GET http://localhost:3000/task